# Generated by Django 4.1.3 on 2023-01-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=7)),
                ('color', models.CharField(max_length=30)),
                ('year', models.IntegerField(max_length=4)),
                ('price', models.IntegerField(max_length=8)),
                ('contact', models.EmailField(max_length=254)),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
    ]
