# Generated by Django 4.1.3 on 2023-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_color_car_in_house_car_km_alter_car_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
