# Generated by Django 4.1.3 on 2023-02-06 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='car',
            name='contact_name',
        ),
    ]
