# Generated by Django 4.1.3 on 2023-02-06 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_alter_car_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={},
        ),
    ]
